"""Regime report generator — produces findings in the regime's voice and aesthetic.

Each report is rendered in markdown using the regime's narrative identity:
voice, aesthetic, character archetype, and soundtrack reference.
"""

from __future__ import annotations

from .auditor import AuditReport
from .divergence import DivergenceResult
from .regime import Regime


def render_report(regime: Regime, report: AuditReport) -> str:
    """Render an audit report in the regime's narrative voice."""
    lines = []

    # Header in regime aesthetic
    lines.append(f"# {regime.narrative.character_archetype}")
    lines.append(f"## Agon Audit: *{regime.name}* ({regime.latin})")
    lines.append("")
    lines.append(f"> *{regime.narrative.voice.strip().split('.')[0]}.*")
    lines.append("")
    lines.append(f"**Cosmology:** {regime.cosmology} | **Aesthetic:** {regime.narrative.aesthetic.strip().split('.')[0]}")
    lines.append(f"**Soundtrack:** {regime.narrative.soundtrack.strip().split('.')[0]}")
    lines.append("")

    # Philosophy framing
    lines.append("---")
    lines.append("")
    lines.append(f"*{regime.philosophy.strip()[:200]}...*")
    lines.append("")

    # Summary
    lines.append("## Findings Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in ("critical", "high", "medium", "low"):
        count = report.summary.get(sev, 0)
        if count > 0:
            lines.append(f"| **{sev.upper()}** | {count} |")
    lines.append(f"| **TOTAL** | {report.summary['total']} |")
    lines.append("")

    # Critical findings first
    criticals = [f for f in report.findings if f.severity == "critical"]
    if criticals:
        lines.append("## Critical Findings")
        lines.append("")
        for f in criticals:
            lines.append(f"- **{f.target}**: {f.description}")
        lines.append("")

    # High findings
    highs = [f for f in report.findings if f.severity == "high"]
    if highs:
        lines.append("## High Findings")
        lines.append("")
        for f in highs:
            lines.append(f"- **{f.target}**: {f.description}")
        lines.append("")

    # Medium and low
    others = [f for f in report.findings if f.severity in ("medium", "low")]
    if others:
        lines.append("## Other Findings")
        lines.append("")
        for f in others:
            lines.append(f"- [{f.severity}] **{f.target}**: {f.description}")
        lines.append("")

    # Phaethon self-check
    lines.append("## Phaethon Self-Assessment")
    lines.append("")
    lines.append(f"**My blind spot:** {regime.phaethon.risk.strip()}")
    lines.append("")
    lines.append(f"**Symptom to watch:** {regime.phaethon.symptom.strip()}")
    lines.append("")
    lines.append(f"**If I fail, summon:** *{regime.phaethon.corrective_regime}*")
    lines.append("")

    lines.append("---")
    lines.append(f"*Report generated by the {regime.name} regime. The Agon continues.*")

    return "\n".join(lines)


def render_divergence_report(
    divergence: DivergenceResult,
    regimes: dict[str, Regime],
) -> str:
    """Render a divergence analysis as markdown."""
    lines = []
    lines.append("# Divergence Analysis — The Agon Speaks")
    lines.append("")
    lines.append(f"**Regimes compared:** {', '.join(divergence.regimes_compared)}")
    lines.append("")

    # Consensus
    lines.append("## Consensus (All Regimes Agree)")
    lines.append("")
    if divergence.constitutional_candidates:
        lines.append("These findings are **Constitutional law candidates** — truth confirmed by every lens:")
        lines.append("")
        for c in divergence.constitutional_candidates:
            lines.append(f"- [{c.severity_ceiling}] **{c.target}**: {c.description}")
    else:
        lines.append("*No consensus yet. The regimes see different worlds. This is expected — convergence takes time.*")
    lines.append("")

    # Unique findings
    lines.append("## Unique Findings (What Only One Regime Sees)")
    lines.append("")
    for regime_id, findings in divergence.unique_findings.items():
        if findings:
            regime = regimes.get(regime_id)
            name = regime.name if regime else regime_id
            lines.append(f"### {name} sees {len(findings)} thing(s) others miss:")
            lines.append("")
            for f in findings[:10]:
                lines.append(f"- [{f.severity}] **{f.target}**: {f.description}")
            if len(findings) > 10:
                lines.append(f"- *...and {len(findings) - 10} more*")
            lines.append("")

    # Perspective divergences
    if divergence.perspective_divergences:
        lines.append("## Perspective Divergences (Same Target, Different Interpretation)")
        lines.append("")
        for pd in divergence.perspective_divergences:
            lines.append(f"### {pd.target}")
            for regime_id, interp in pd.interpretations.items():
                regime = regimes.get(regime_id)
                name = regime.name if regime else regime_id
                lines.append(f"- **{name}**: {interp}")
            lines.append("")

    # Priority conflicts
    if divergence.priority_conflicts:
        lines.append("## Priority Conflicts (Same Finding, Different Severity)")
        lines.append("")
        for pc in divergence.priority_conflicts:
            lines.append(f"- **{pc.target}**: {pc.description}")
            for regime_id, sev in pc.severities.items():
                lines.append(f"  - {regime_id}: {sev}")
            lines.append(f"  - **Ceiling:** {pc.ceiling}")
            lines.append("")

    lines.append("---")
    lines.append("*The Agon does not require agreement. Divergence is data, not failure.*")

    return "\n".join(lines)
